[package]
name = "lyra"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["cors"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
nix = { version = "0.30.1", features = ["signal"] }
notify = "8.1.0"
libc = "0.2.174"
easy-ffprobe = "0.5.2"
reqwest = { version = "0.12", features = ["stream", "json"] }
tar = "0.4"
xz2 = "0.1"
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "macros",
    "sqlite",
    "migrate",
    "chrono",
] }
once_cell = "1.21.3"
config = { version = "0.15", features = ["yaml"] }
chrono = { version = "0.4", features = ["serde"] }
torrent-name-parser = "0.12.1"
async-graphql = { version = "7.0.14", features = ["dataloader"] }
async-graphql-axum = "7.0.14"
lru = "0.12"
ratelimit = "0.10.0"
image = { version = "0.24", features = ["jpeg"] }
sha2 = "0.10"
hex = "0.4.3"
tokio-util = "0.7.15"
futures-util = "0.3.31"
thumbhash = "0.1.0"
rand = "0.9.1"
tempfile = "3.20.0"
sea-orm = { version = "1.1", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "runtime-tokio",
    "macros",
    "debug-print",
    "sqlite-use-returning-for-3_35",
] }
bitflags = "2.9.1"
argon2 = { version = "^0.5.3", default-features = false, features = [
    "alloc",
    "password-hash",
    "rand",
    "std",
] }
axum-extra = { version = "0.10.1", features = ["cookie"] }
ulid = "1.2.1"
cookie = "0.18.1"
regex = "1.11.1"

# force the image crate to use a release build even if we're in debug mode
# otherwise images are painfully slow to load
[profile.dev.package.image]
opt-level = 3
[profile.dev.package.zune-core]
opt-level = 3
[profile.dev.package.zune-jpeg]
opt-level = 3
