[package]
name = "lyra"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0.140"
tempfile = "3.20.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["cors"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
nix = { version = "0.30.1", features = ["signal"] }
notify = "8.1.0"
libc = "0.2.174"
easy-ffprobe = "0.5.2"
reqwest = { version = "0.12", features = ["stream"] }
tar = "0.4"
xz2 = "0.1"
