//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Hash)]
#[sea_orm(rs_type = "i64", db_type = "Integer")]
pub enum JobType {
    #[sea_orm(num_value = 0)]
    FileGenerateTimelinePreview,
    #[sea_orm(num_value = 1)]
    FileGenerateThumbnail,
    #[sea_orm(num_value = 2)]
    FileExtractFfprobe,
    #[sea_orm(num_value = 3)]
    FileExtractKeyframes,
}

impl JobType {
    pub const fn code(self) -> i64 {
        match self {
            JobType::FileGenerateTimelinePreview => 0,
            JobType::FileGenerateThumbnail => 1,
            JobType::FileExtractFfprobe => 2,
            JobType::FileExtractKeyframes => 3,
        }
    }

    pub const fn title(self) -> &'static str {
        match self {
            JobType::FileGenerateTimelinePreview => "Timeline Preview",
            JobType::FileGenerateThumbnail => "Thumbnail",
            JobType::FileExtractFfprobe => "FFprobe",
            JobType::FileExtractKeyframes => "Keyframes",
        }
    }
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "i64", db_type = "Integer")]
pub enum JobStatus {
    #[sea_orm(num_value = 0)]
    Success,
    #[sea_orm(num_value = 1)]
    Error,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub job_type: JobType,
    pub file_id: i64,
    pub status: JobStatus,
    pub attempt_count: i64,
    pub next_retry_at: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error_message: Option<String>,
    pub last_run_at: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::files::Entity",
        from = "Column::FileId",
        to = "super::files::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Files,
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
