//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use crate::tasks::TaskScopeKind;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub task_type: String,
    pub scope_kind: TaskScopeKind,
    #[sea_orm(column_type = "Text")]
    pub scope_id: String,
    #[sea_orm(column_type = "Blob", nullable)]
    pub input_args: Option<Vec<u8>>,
    pub version_number: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub version_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error_message: Option<String>,
    pub last_run_at: Option<i64>,
    pub execute_after: Option<i64>,
    pub locked_at: Option<i64>,
    pub attempt_count: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
