/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'ActiveTask': { kind: 'OBJECT'; name: 'ActiveTask'; fields: { 'current': { name: 'current'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'progressPercent': { name: 'progressPercent'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'taskType': { name: 'taskType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'total': { name: 'total'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Boolean': unknown;
    'File': { kind: 'OBJECT'; name: 'File'; fields: { 'corruptedAt': { name: 'corruptedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'discoveredAt': { name: 'discoveredAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'editionName': { name: 'editionName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'height': { name: 'height'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'libraryId': { name: 'libraryId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'relativePath': { name: 'relativePath'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'scannedAt': { name: 'scannedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'sizeBytes': { name: 'sizeBytes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'unavailableAt': { name: 'unavailableAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'width': { name: 'width'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'Float': unknown;
    'Int': unknown;
    'ItemKind': { name: 'ItemKind'; enumValues: 'MOVIE' | 'EPISODE'; };
    'ItemNode': { kind: 'OBJECT'; name: 'ItemNode'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'episodeNumber': { name: 'episodeNumber'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'file': { name: 'file'; type: { kind: 'OBJECT'; name: 'File'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'kind': { name: 'kind'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'ItemKind'; ofType: null; }; } }; 'lastAddedAt': { name: 'lastAddedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'order': { name: 'order'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'parent': { name: 'parent'; type: { kind: 'OBJECT'; name: 'RootNode'; ofType: null; } }; 'primaryFileId': { name: 'primaryFileId'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'properties': { name: 'properties'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ItemNodeProperties'; ofType: null; }; } }; 'rootId': { name: 'rootId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'seasonId': { name: 'seasonId'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'watchProgress': { name: 'watchProgress'; type: { kind: 'OBJECT'; name: 'WatchProgress'; ofType: null; } }; }; };
    'ItemNodeConnection': { kind: 'OBJECT'; name: 'ItemNodeConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ItemNodeEdge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ItemNode'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'ItemNodeEdge': { kind: 'OBJECT'; name: 'ItemNodeEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ItemNode'; ofType: null; }; } }; }; };
    'ItemNodeFilter': { kind: 'INPUT_OBJECT'; name: 'ItemNodeFilter'; isOneOf: false; inputFields: [{ name: 'rootId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'seasonNumbers'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; }; defaultValue: null }, { name: 'orderBy'; type: { kind: 'ENUM'; name: 'ItemNodeOrderBy'; ofType: null; }; defaultValue: null }, { name: 'orderDirection'; type: { kind: 'ENUM'; name: 'OrderDirection'; ofType: null; }; defaultValue: null }, { name: 'watched'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }]; };
    'ItemNodeOrderBy': { name: 'ItemNodeOrderBy'; enumValues: 'ADDED_AT' | 'RELEASED_AT' | 'ALPHABETICAL' | 'RATING' | 'SEASON_EPISODE'; };
    'ItemNodeProperties': { kind: 'OBJECT'; name: 'ItemNodeProperties'; fields: { 'backgroundUrl': { name: 'backgroundUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'endedAt': { name: 'endedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'episodeNumber': { name: 'episodeNumber'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'posterUrl': { name: 'posterUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'rating': { name: 'rating'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'releasedAt': { name: 'releasedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'runtimeMinutes': { name: 'runtimeMinutes'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'seasonNumber': { name: 'seasonNumber'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'thumbnailUrl': { name: 'thumbnailUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'Library': { kind: 'OBJECT'; name: 'Library'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'lastScannedAt': { name: 'lastScannedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'createLibrary': { name: 'createLibrary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Library'; ofType: null; }; } }; 'signup': { name: 'signup'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'updateWatchProgress': { name: 'updateWatchProgress'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'WatchProgress'; ofType: null; }; }; }; } }; }; };
    'OrderDirection': { name: 'OrderDirection'; enumValues: 'ASC' | 'DESC'; };
    'PageInfo': { kind: 'OBJECT'; name: 'PageInfo'; fields: { 'endCursor': { name: 'endCursor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'hasNextPage': { name: 'hasNextPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'hasPreviousPage': { name: 'hasPreviousPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'startCursor': { name: 'startCursor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'activeTasks': { name: 'activeTasks'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ActiveTask'; ofType: null; }; }; }; } }; 'item': { name: 'item'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ItemNode'; ofType: null; }; } }; 'itemList': { name: 'itemList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ItemNodeConnection'; ofType: null; }; } }; 'libraries': { name: 'libraries'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Library'; ofType: null; }; }; }; } }; 'listFiles': { name: 'listFiles'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'root': { name: 'root'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RootNode'; ofType: null; }; } }; 'rootList': { name: 'rootList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RootNodeConnection'; ofType: null; }; } }; 'season': { name: 'season'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SeasonNode'; ofType: null; }; } }; }; };
    'RootChild': { kind: 'UNION'; name: 'RootChild'; fields: {}; possibleTypes: 'ItemNode' | 'SeasonNode'; };
    'RootKind': { name: 'RootKind'; enumValues: 'MOVIE' | 'SERIES'; };
    'RootNode': { kind: 'OBJECT'; name: 'RootNode'; fields: { 'children': { name: 'children'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'RootChild'; ofType: null; }; }; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'files': { name: 'files'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ItemNode'; ofType: null; }; }; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'kind': { name: 'kind'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'RootKind'; ofType: null; }; } }; 'lastAddedAt': { name: 'lastAddedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'libraryId': { name: 'libraryId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'playableItem': { name: 'playableItem'; type: { kind: 'OBJECT'; name: 'ItemNode'; ofType: null; } }; 'properties': { name: 'properties'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RootNodeProperties'; ofType: null; }; } }; 'seasons': { name: 'seasons'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SeasonNode'; ofType: null; }; }; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'watchProgress': { name: 'watchProgress'; type: { kind: 'OBJECT'; name: 'WatchProgress'; ofType: null; } }; }; };
    'RootNodeConnection': { kind: 'OBJECT'; name: 'RootNodeConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RootNodeEdge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RootNode'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'RootNodeEdge': { kind: 'OBJECT'; name: 'RootNodeEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'RootNode'; ofType: null; }; } }; }; };
    'RootNodeFilter': { kind: 'INPUT_OBJECT'; name: 'RootNodeFilter'; isOneOf: false; inputFields: [{ name: 'libraryId'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'kinds'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'RootKind'; ofType: null; }; }; }; defaultValue: null }, { name: 'orderBy'; type: { kind: 'ENUM'; name: 'RootNodeOrderBy'; ofType: null; }; defaultValue: null }, { name: 'orderDirection'; type: { kind: 'ENUM'; name: 'OrderDirection'; ofType: null; }; defaultValue: null }, { name: 'watched'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }]; };
    'RootNodeOrderBy': { name: 'RootNodeOrderBy'; enumValues: 'ADDED_AT' | 'RELEASED_AT' | 'ALPHABETICAL' | 'RATING' | 'SEASON_EPISODE'; };
    'RootNodeProperties': { kind: 'OBJECT'; name: 'RootNodeProperties'; fields: { 'backgroundUrl': { name: 'backgroundUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'endedAt': { name: 'endedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'posterUrl': { name: 'posterUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'rating': { name: 'rating'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'releasedAt': { name: 'releasedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'runtimeMinutes': { name: 'runtimeMinutes'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'thumbnailUrl': { name: 'thumbnailUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'SeasonNode': { kind: 'OBJECT'; name: 'SeasonNode'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'files': { name: 'files'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ItemNode'; ofType: null; }; }; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'lastAddedAt': { name: 'lastAddedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'order': { name: 'order'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'playableItem': { name: 'playableItem'; type: { kind: 'OBJECT'; name: 'ItemNode'; ofType: null; } }; 'properties': { name: 'properties'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SeasonNodeProperties'; ofType: null; }; } }; 'rootId': { name: 'rootId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'seasonNumber': { name: 'seasonNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'watchProgress': { name: 'watchProgress'; type: { kind: 'OBJECT'; name: 'WatchProgress'; ofType: null; } }; }; };
    'SeasonNodeProperties': { kind: 'OBJECT'; name: 'SeasonNodeProperties'; fields: { 'backgroundUrl': { name: 'backgroundUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'endedAt': { name: 'endedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'posterUrl': { name: 'posterUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'rating': { name: 'rating'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'releasedAt': { name: 'releasedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'runtimeMinutes': { name: 'runtimeMinutes'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'seasonNumber': { name: 'seasonNumber'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'thumbnailUrl': { name: 'thumbnailUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'String': unknown;
    'User': { kind: 'OBJECT'; name: 'User'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'defaultAudioIso6391': { name: 'defaultAudioIso6391'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'defaultSubtitleIso6391': { name: 'defaultSubtitleIso6391'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'permissions': { name: 'permissions'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'subtitlesEnabled': { name: 'subtitlesEnabled'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'username': { name: 'username'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'WatchProgress': { kind: 'OBJECT'; name: 'WatchProgress'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'fileId': { name: 'fileId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'itemId': { name: 'itemId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'progressPercent': { name: 'progressPercent'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'userId': { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}
