/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Boolean': unknown;
    'File': { kind: 'OBJECT'; name: 'File'; fields: { 'corruptedAt': { name: 'corruptedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'editionName': { name: 'editionName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'libraryId': { name: 'libraryId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'pendingAutoMatch': { name: 'pendingAutoMatch'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'relativePath': { name: 'relativePath'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'resolution': { name: 'resolution'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'scannedAt': { name: 'scannedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'sizeBytes': { name: 'sizeBytes'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'unavailableAt': { name: 'unavailableAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'Float': unknown;
    'Int': unknown;
    'Library': { kind: 'OBJECT'; name: 'Library'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'lastScannedAt': { name: 'lastScannedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Media': { kind: 'OBJECT'; name: 'Media'; fields: { 'backgroundUrl': { name: 'backgroundUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'defaultConnection': { name: 'defaultConnection'; type: { kind: 'OBJECT'; name: 'File'; ofType: null; } }; 'description': { name: 'description'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'endedAt': { name: 'endedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'episodeNumber': { name: 'episodeNumber'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'firstLinkedAt': { name: 'firstLinkedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'imdbId': { name: 'imdbId'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'kind': { name: 'kind'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'MediaKind'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'parent': { name: 'parent'; type: { kind: 'OBJECT'; name: 'Media'; ofType: null; } }; 'parentId': { name: 'parentId'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'posterUrl': { name: 'posterUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'rating': { name: 'rating'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'releasedAt': { name: 'releasedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'runtimeMinutes': { name: 'runtimeMinutes'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'seasonNumber': { name: 'seasonNumber'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'seasons': { name: 'seasons'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; }; } }; 'thumbnailUrl': { name: 'thumbnailUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'tmdbId': { name: 'tmdbId'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'watchState': { name: 'watchState'; type: { kind: 'OBJECT'; name: 'WatchState'; ofType: null; } }; }; };
    'MediaConnection': { kind: 'OBJECT'; name: 'MediaConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaEdge'; ofType: null; }; }; }; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Media'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'MediaEdge': { kind: 'OBJECT'; name: 'MediaEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Media'; ofType: null; }; } }; }; };
    'MediaFilter': { kind: 'INPUT_OBJECT'; name: 'MediaFilter'; isOneOf: false; inputFields: [{ name: 'parentId'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'seasonNumbers'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; }; defaultValue: null }, { name: 'kinds'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'MediaKind'; ofType: null; }; }; }; defaultValue: null }, { name: 'search'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'orderBy'; type: { kind: 'ENUM'; name: 'MediaOrderBy'; ofType: null; }; defaultValue: null }, { name: 'orderDirection'; type: { kind: 'ENUM'; name: 'OrderDirection'; ofType: null; }; defaultValue: null }, { name: 'watched'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }]; };
    'MediaKind': { name: 'MediaKind'; enumValues: 'MOVIE' | 'SHOW' | 'EPISODE'; };
    'MediaOrderBy': { name: 'MediaOrderBy'; enumValues: 'ADDED_AT' | 'RELEASED_AT' | 'ALPHABETICAL' | 'RATING' | 'SEASON_EPISODE'; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'createLibrary': { name: 'createLibrary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Library'; ofType: null; }; } }; 'signup': { name: 'signup'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'updateWatchState': { name: 'updateWatchState'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'WatchState'; ofType: null; }; } }; }; };
    'OrderDirection': { name: 'OrderDirection'; enumValues: 'ASC' | 'DESC'; };
    'PageInfo': { kind: 'OBJECT'; name: 'PageInfo'; fields: { 'endCursor': { name: 'endCursor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'hasNextPage': { name: 'hasNextPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'hasPreviousPage': { name: 'hasPreviousPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'startCursor': { name: 'startCursor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'libraries': { name: 'libraries'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Library'; ofType: null; }; }; }; } }; 'listFiles': { name: 'listFiles'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'media': { name: 'media'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Media'; ofType: null; }; } }; 'mediaList': { name: 'mediaList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MediaConnection'; ofType: null; }; } }; }; };
    'String': unknown;
    'User': { kind: 'OBJECT'; name: 'User'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'defaultAudioBcp47': { name: 'defaultAudioBcp47'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'defaultSubtitleBcp47': { name: 'defaultSubtitleBcp47'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'permissions': { name: 'permissions'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'subtitlesEnabled': { name: 'subtitlesEnabled'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'username': { name: 'username'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'WatchState': { kind: 'OBJECT'; name: 'WatchState'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'mediaId': { name: 'mediaId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'progressPercentage': { name: 'progressPercentage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'userId': { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}