/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SetupRouteImport } from './../routes/setup'
import { Route as SettingsRouteImport } from './../routes/settings'
import { Route as PlaygroundRouteImport } from './../routes/playground'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SettingsIndexRouteImport } from './../routes/settings.index'
import { Route as SetupLoginRouteImport } from './../routes/setup.login'
import { Route as SetupCreateLibraryRouteImport } from './../routes/setup.create-library'
import { Route as SetupCreateAccountRouteImport } from './../routes/setup.create-account'
import { Route as SettingsLibrariesRouteImport } from './../routes/settings.libraries'
import { Route as SettingsImportRouteImport } from './../routes/settings.import'
import { Route as SettingsAboutRouteImport } from './../routes/settings.about'
import { Route as LibraryLibraryIdRouteImport } from './../routes/library.$libraryId'
import { Route as LibraryLibraryIdNodeNodeIdRouteImport } from './../routes/library_.$libraryId.node_.$nodeId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SetupLoginRoute = SetupLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SetupRoute,
} as any)
const SetupCreateLibraryRoute = SetupCreateLibraryRouteImport.update({
  id: '/create-library',
  path: '/create-library',
  getParentRoute: () => SetupRoute,
} as any)
const SetupCreateAccountRoute = SetupCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => SetupRoute,
} as any)
const SettingsLibrariesRoute = SettingsLibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsImportRoute = SettingsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const LibraryLibraryIdRoute = LibraryLibraryIdRouteImport.update({
  id: '/library/$libraryId',
  path: '/library/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryLibraryIdNodeNodeIdRoute =
  LibraryLibraryIdNodeNodeIdRouteImport.update({
    id: '/library_/$libraryId/node_/$nodeId',
    path: '/library/$libraryId/node/$nodeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRouteWithChildren
  '/library/$libraryId': typeof LibraryLibraryIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/libraries': typeof SettingsLibrariesRoute
  '/setup/create-account': typeof SetupCreateAccountRoute
  '/setup/create-library': typeof SetupCreateLibraryRoute
  '/setup/login': typeof SetupLoginRoute
  '/settings/': typeof SettingsIndexRoute
  '/library/$libraryId/node/$nodeId': typeof LibraryLibraryIdNodeNodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/setup': typeof SetupRouteWithChildren
  '/library/$libraryId': typeof LibraryLibraryIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/libraries': typeof SettingsLibrariesRoute
  '/setup/create-account': typeof SetupCreateAccountRoute
  '/setup/create-library': typeof SetupCreateLibraryRoute
  '/setup/login': typeof SetupLoginRoute
  '/settings': typeof SettingsIndexRoute
  '/library/$libraryId/node/$nodeId': typeof LibraryLibraryIdNodeNodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRouteWithChildren
  '/library/$libraryId': typeof LibraryLibraryIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/import': typeof SettingsImportRoute
  '/settings/libraries': typeof SettingsLibrariesRoute
  '/setup/create-account': typeof SetupCreateAccountRoute
  '/setup/create-library': typeof SetupCreateLibraryRoute
  '/setup/login': typeof SetupLoginRoute
  '/settings/': typeof SettingsIndexRoute
  '/library_/$libraryId/node_/$nodeId': typeof LibraryLibraryIdNodeNodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/settings'
    | '/setup'
    | '/library/$libraryId'
    | '/settings/about'
    | '/settings/import'
    | '/settings/libraries'
    | '/setup/create-account'
    | '/setup/create-library'
    | '/setup/login'
    | '/settings/'
    | '/library/$libraryId/node/$nodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/setup'
    | '/library/$libraryId'
    | '/settings/about'
    | '/settings/import'
    | '/settings/libraries'
    | '/setup/create-account'
    | '/setup/create-library'
    | '/setup/login'
    | '/settings'
    | '/library/$libraryId/node/$nodeId'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/settings'
    | '/setup'
    | '/library/$libraryId'
    | '/settings/about'
    | '/settings/import'
    | '/settings/libraries'
    | '/setup/create-account'
    | '/setup/create-library'
    | '/setup/login'
    | '/settings/'
    | '/library_/$libraryId/node_/$nodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRouteWithChildren
  LibraryLibraryIdRoute: typeof LibraryLibraryIdRoute
  LibraryLibraryIdNodeNodeIdRoute: typeof LibraryLibraryIdNodeNodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/setup/login': {
      id: '/setup/login'
      path: '/login'
      fullPath: '/setup/login'
      preLoaderRoute: typeof SetupLoginRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/create-library': {
      id: '/setup/create-library'
      path: '/create-library'
      fullPath: '/setup/create-library'
      preLoaderRoute: typeof SetupCreateLibraryRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/create-account': {
      id: '/setup/create-account'
      path: '/create-account'
      fullPath: '/setup/create-account'
      preLoaderRoute: typeof SetupCreateAccountRouteImport
      parentRoute: typeof SetupRoute
    }
    '/settings/libraries': {
      id: '/settings/libraries'
      path: '/libraries'
      fullPath: '/settings/libraries'
      preLoaderRoute: typeof SettingsLibrariesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/import': {
      id: '/settings/import'
      path: '/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof SettingsImportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/library/$libraryId': {
      id: '/library/$libraryId'
      path: '/library/$libraryId'
      fullPath: '/library/$libraryId'
      preLoaderRoute: typeof LibraryLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$libraryId/node_/$nodeId': {
      id: '/library_/$libraryId/node_/$nodeId'
      path: '/library/$libraryId/node/$nodeId'
      fullPath: '/library/$libraryId/node/$nodeId'
      preLoaderRoute: typeof LibraryLibraryIdNodeNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsImportRoute: typeof SettingsImportRoute
  SettingsLibrariesRoute: typeof SettingsLibrariesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsImportRoute: SettingsImportRoute,
  SettingsLibrariesRoute: SettingsLibrariesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SetupRouteChildren {
  SetupCreateAccountRoute: typeof SetupCreateAccountRoute
  SetupCreateLibraryRoute: typeof SetupCreateLibraryRoute
  SetupLoginRoute: typeof SetupLoginRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupCreateAccountRoute: SetupCreateAccountRoute,
  SetupCreateLibraryRoute: SetupCreateLibraryRoute,
  SetupLoginRoute: SetupLoginRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRouteWithChildren,
  LibraryLibraryIdRoute: LibraryLibraryIdRoute,
  LibraryLibraryIdNodeNodeIdRoute: LibraryLibraryIdNodeNodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
