/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as PlaygroundRouteImport } from './../routes/playground'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as LibraryLibraryIdRouteImport } from './../routes/library.$libraryId'
import { Route as LibraryLibraryIdRootIdRouteImport } from './../routes/library_.$libraryId.$rootId'
import { Route as LibraryLibraryIdRootIdSeasonIdRouteImport } from './../routes/library_.$libraryId.$rootId_.$seasonId'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryLibraryIdRoute = LibraryLibraryIdRouteImport.update({
  id: '/library/$libraryId',
  path: '/library/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryLibraryIdRootIdRoute = LibraryLibraryIdRootIdRouteImport.update({
  id: '/library_/$libraryId/$rootId',
  path: '/library/$libraryId/$rootId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryLibraryIdRootIdSeasonIdRoute =
  LibraryLibraryIdRootIdSeasonIdRouteImport.update({
    id: '/library_/$libraryId/$rootId_/$seasonId',
    path: '/library/$libraryId/$rootId/$seasonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/library/$libraryId': typeof LibraryLibraryIdRoute
  '/library/$libraryId/$rootId': typeof LibraryLibraryIdRootIdRoute
  '/library/$libraryId/$rootId/$seasonId': typeof LibraryLibraryIdRootIdSeasonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/library/$libraryId': typeof LibraryLibraryIdRoute
  '/library/$libraryId/$rootId': typeof LibraryLibraryIdRootIdRoute
  '/library/$libraryId/$rootId/$seasonId': typeof LibraryLibraryIdRootIdSeasonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/library/$libraryId': typeof LibraryLibraryIdRoute
  '/library_/$libraryId/$rootId': typeof LibraryLibraryIdRootIdRoute
  '/library_/$libraryId/$rootId_/$seasonId': typeof LibraryLibraryIdRootIdSeasonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/library/$libraryId'
    | '/library/$libraryId/$rootId'
    | '/library/$libraryId/$rootId/$seasonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/library/$libraryId'
    | '/library/$libraryId/$rootId'
    | '/library/$libraryId/$rootId/$seasonId'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/library/$libraryId'
    | '/library_/$libraryId/$rootId'
    | '/library_/$libraryId/$rootId_/$seasonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  LibraryLibraryIdRoute: typeof LibraryLibraryIdRoute
  LibraryLibraryIdRootIdRoute: typeof LibraryLibraryIdRootIdRoute
  LibraryLibraryIdRootIdSeasonIdRoute: typeof LibraryLibraryIdRootIdSeasonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$libraryId': {
      id: '/library/$libraryId'
      path: '/library/$libraryId'
      fullPath: '/library/$libraryId'
      preLoaderRoute: typeof LibraryLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$libraryId/$rootId': {
      id: '/library_/$libraryId/$rootId'
      path: '/library/$libraryId/$rootId'
      fullPath: '/library/$libraryId/$rootId'
      preLoaderRoute: typeof LibraryLibraryIdRootIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$libraryId/$rootId_/$seasonId': {
      id: '/library_/$libraryId/$rootId_/$seasonId'
      path: '/library/$libraryId/$rootId/$seasonId'
      fullPath: '/library/$libraryId/$rootId/$seasonId'
      preLoaderRoute: typeof LibraryLibraryIdRootIdSeasonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  LibraryLibraryIdRoute: LibraryLibraryIdRoute,
  LibraryLibraryIdRootIdRoute: LibraryLibraryIdRootIdRoute,
  LibraryLibraryIdRootIdSeasonIdRoute: LibraryLibraryIdRootIdSeasonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
