use crate::{
    AppState,
    assets::{AssetPayload, storage},
    auth::LazyRequestAuth,
    entities::assets as assets_entity,
    error::AppError,
    jobs::{self, AssetDownloadJob},
    signer::verify,
};
use axum::{
    Router,
    body::Body,
    extract::{Path, Query, State},
    response::{IntoResponse, Response},
    routing::get,
};
use image::{GenericImageView, ImageOutputFormat, imageops::FilterType};
use reqwest::header::{CACHE_CONTROL, CONTENT_LENGTH, CONTENT_TYPE};
use sea_orm::EntityTrait;
use serde::Deserialize;
use std::{io::Cursor, path::Path as FsPath, time::Duration};
use tokio::{fs::File, task::spawn_blocking};
use tokio_util::io::ReaderStream;

const ON_DEMAND_JOB_TIMEOUT: Duration = Duration::from_secs(120);

#[derive(Debug, Deserialize, Clone)]
pub struct TranscodeParams {
    pub width: Option<u32>,
    pub height: Option<u32>,
}

pub fn get_assets_router() -> Router<AppState> {
    Router::new().route("/{asset_id}/{signature}", get(get_asset))
}

// this route does not need auth because we used signed urls that can only be generated by users
// todo: we should switch to signed tokens and require a signed auth token, but without validating it
// that means we know that: they have a signed url *and* they are very likely an authed user
async fn get_asset(
    _lazy_auth: LazyRequestAuth,
    State(state): State<AppState>,
    Path((_unchecked_asset_id, signature)): Path<(String, String)>,
    Query(params): Query<TranscodeParams>,
) -> Result<Response, AppError> {
    let (_expires_in, payload) = verify::<AssetPayload>(&signature)?;
    let mut asset = assets_entity::Entity::find_by_id(&payload.asset_id)
        .one(&state.pool)
        .await?
        .ok_or_else(|| anyhow::anyhow!("asset not found"))?;

    if asset.hash_sha256.is_none() {
        jobs::try_run_job(
            &state.pool,
            &AssetDownloadJob,
            asset.clone(),
            ON_DEMAND_JOB_TIMEOUT,
        )
        .await?;

        asset = assets_entity::Entity::find_by_id(asset.id.clone())
            .one(&state.pool)
            .await?
            .ok_or_else(|| anyhow::anyhow!("asset disappeared after download job"))?;
    }

    Ok(serve_asset(&asset, &params).await?)
}

async fn serve_asset(
    asset: &assets_entity::Model,
    params: &TranscodeParams,
) -> Result<Response, AppError> {
    let hash_sha256 = asset
        .hash_sha256
        .as_deref()
        .ok_or_else(|| anyhow::anyhow!("asset has no local hash"))?;
    let mime_type = asset
        .mime_type
        .as_deref()
        .ok_or_else(|| anyhow::anyhow!("asset has no mime_type"))?;

    let original_path = storage::get_asset_output_path_from_mime(hash_sha256, mime_type)?;
    if params.width.is_none() && params.height.is_none() {
        return stream_file(&original_path, mime_type).await;
    }

    let transformed_path =
        storage::get_transformed_cache_path(hash_sha256, params.width, params.height);

    if !tokio::fs::try_exists(&transformed_path).await? {
        let target_width = params.width;
        let target_height = params.height;

        // Run image decoding and resizing off the async runtime and capture only owned values.
        let bytes = spawn_blocking(move || -> anyhow::Result<Vec<u8>> {
            let original_bytes = std::fs::read(&original_path)
                .map_err(|err| anyhow::anyhow!("failed reading source asset file: {err}"))?;
            let image = image::load_from_memory(&original_bytes)?;

            let (original_width, original_height) = image.dimensions();
            let target_width = target_width.unwrap_or(original_width);
            let target_height = target_height.unwrap_or(original_height);

            let resized = image.resize(target_width, target_height, FilterType::Lanczos3);

            let mut cursor = Cursor::new(Vec::new());
            resized.write_to(&mut cursor, ImageOutputFormat::Jpeg(80))?;
            Ok(cursor.into_inner())
        })
        .await??;

        storage::persist_bytes_atomically(&transformed_path, &bytes).await?;
    }

    stream_file(&transformed_path, "image/jpeg").await
}

async fn stream_file(path: &FsPath, content_type: &str) -> Result<Response, AppError> {
    let file = File::open(path).await?;
    let metadata = file.metadata().await?;

    let stream = ReaderStream::new(file);
    let body = Body::from_stream(stream);

    let headers = [
        (CONTENT_LENGTH, metadata.len().to_string()),
        (CONTENT_TYPE, content_type.to_string()),
        (
            CACHE_CONTROL,
            "public, max-age=31536000, immutable".to_string(),
        ),
    ];

    Ok((headers, body).into_response())
}
